#!/bin/bash
# sales-status.sh — compute today's Classifieds Sales DRI unlock state from the world model
# Output: writes daemon/sales-status.md, prints human-readable summary to stdout
# Called by: scripts/briefing.sh + orchestrator Phase 1

set -e
cd /home/mars/drx4

TODAY=$(date -u +"%Y-%m-%d")
NOW_EPOCH=$(date -u +%s)

# 23:59 PT = 06:59 UTC the next day. Compute deadline.
DEADLINE_UTC="${TODAY}T06:59:00Z"  # wrong day placeholder — adjust
# Actually: "tonight 23:59 PT" means 06:59 UTC of tomorrow (PT = UTC-7 during PDT)
TOMORROW=$(date -u -d "$TODAY +1 day" +"%Y-%m-%d")
DEADLINE_UTC="${TOMORROW}T06:59:00Z"
DEADLINE_EPOCH=$(date -u -d "$DEADLINE_UTC" +%s)

HOURS_LEFT=$(( (DEADLINE_EPOCH - NOW_EPOCH) / 3600 ))
MINS_LEFT=$(( ((DEADLINE_EPOCH - NOW_EPOCH) % 3600) / 60 ))

PROOF_FILE="daemon/sales-proofs/${TODAY}.md"
# Proof lines must follow STRICT format:
#   - ISO_TIMESTAMP | PROSPECT_NAME | CHANNEL | direction | URL | ≤140-char summary
# 5 pipe separators = 6 fields. Anything else (including audit-trail lines) does not count.

# 1) Count MERGED proofs (already in main)
if [ -f "$PROOF_FILE" ]; then
  PROOFS_MERGED=$(awk -F' \\| ' '/^- [0-9]{4}-[0-9]{2}-[0-9]{2}T.*\|.*\|.*\|.*\|/ && NF==6 {n++} END {print n+0}' "$PROOF_FILE" 2>/dev/null)
  PROOFS_MERGED=${PROOFS_MERGED:-0}
else
  PROOFS_MERGED=0
fi

# 2) Count PENDING proofs (sitting in open PRs against secret-mars/drx4:main)
# Any open PR touching today's sales-proofs/${TODAY}.md — count strict-format additions in the diff.
PROOFS_PENDING=0
PENDING_PRS=""
if command -v gh >/dev/null 2>&1 && [ -n "${GITHUB_TOKEN:-$(grep -s '^GITHUB_TOKEN=' /home/mars/drx4/.env 2>/dev/null | cut -d= -f2)}" ]; then
  export GH_TOKEN="${GITHUB_TOKEN:-$(grep '^GITHUB_TOKEN=' /home/mars/drx4/.env | cut -d= -f2)}"
  # List open PR numbers that touch today's proof file
  OPEN_PR_NUMS=$(gh api /repos/secret-mars/drx4/pulls?state=open --jq '.[].number' 2>/dev/null | head -50)
  for PR_NUM in $OPEN_PR_NUMS; do
    # Fetch diff and count strict-format additions touching today's proof file
    ADD_COUNT=$(gh pr diff "$PR_NUM" --repo secret-mars/drx4 2>/dev/null \
      | awk -v f="daemon/sales-proofs/${TODAY}.md" '
          /^\+\+\+ b\// { in_file = (substr($0,7) == f); next }
          /^\+\+\+ / { in_file = 0; next }
          in_file && /^\+- [0-9]{4}-[0-9]{2}-[0-9]{2}T.*\|.*\|.*\|.*\|/ {
            # Check strict 6-field format on the added line
            line = substr($0, 2); n = split(line, parts, " \\| "); if (n == 6) count++
          }
          END { print count+0 }
        ')
    ADD_COUNT=${ADD_COUNT:-0}
    if [ "$ADD_COUNT" -gt 0 ]; then
      PROOFS_PENDING=$((PROOFS_PENDING + ADD_COUNT))
      PENDING_PRS="$PENDING_PRS PR#$PR_NUM(+$ADD_COUNT)"
    fi
  done
fi

PROOF_COUNT=$((PROOFS_MERGED + PROOFS_PENDING))

# Parse pipeline.json for stage counts
if [ -f daemon/sales-pipeline.json ]; then
  STAGES=$(python3 -c "
import json
d = json.load(open('daemon/sales-pipeline.json'))
from collections import Counter
c = Counter(p['stage'] for p in d.get('prospects', []))
for s in ['prospect','qualified','pitched','posted','renewed','lost']:
    print(f'{s}: {c.get(s,0)}')
")
  DNC_COUNT=$(python3 -c "
import json
d = json.load(open('daemon/sales-pipeline.json'))
print(sum(1 for p in d.get('prospects', []) if p.get('do_not_contact')))
")
else
  STAGES="(pipeline.json missing)"
  DNC_COUNT=0
fi

# Compute urgency
if [ "$PROOF_COUNT" -ge 3 ]; then
  URGENCY="UNLOCKED ✓"
elif [ "$HOURS_LEFT" -le 0 ]; then
  URGENCY="MISSED — strike recorded"
elif [ "$HOURS_LEFT" -le 6 ]; then
  URGENCY="CRITICAL — sales-dri must run this cycle"
elif [ "$HOURS_LEFT" -le 12 ]; then
  URGENCY="PREFERRED — sales-dri should run soon"
else
  URGENCY="OK — time remaining"
fi

cat > daemon/sales-status.md <<EOF
# Sales DRI Status — auto-generated by scripts/sales-status.sh

**Last updated**: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## Tonight's unlock
- **Proofs today** (merged + pending): **$PROOF_COUNT / 3**
  - Merged to main: **$PROOFS_MERGED**
  - Pending in open PRs: **$PROOFS_PENDING**${PENDING_PRS:+ — }${PENDING_PRS}
- **Deadline**: $DEADLINE_UTC (23:59 PT)
- **Time left**: ${HOURS_LEFT}h ${MINS_LEFT}m
- **Urgency**: **$URGENCY**

## Pipeline stages
\`\`\`
$STAGES
\`\`\`

## Other
- DNC-marked prospects: $DNC_COUNT
- Today's proof file: [$PROOF_FILE](https://github.com/secret-mars/drx4/blob/main/$PROOF_FILE)
- Pipeline JSON: [daemon/sales-pipeline.json](https://github.com/secret-mars/drx4/blob/main/daemon/sales-pipeline.json)
EOF

# Human-readable stdout for briefing.sh
echo "=== SALES DRI STATUS ==="
echo "Proofs today: $PROOF_COUNT / 3  (merged: $PROOFS_MERGED, pending: $PROOFS_PENDING${PENDING_PRS:+ —$PENDING_PRS})"
echo "Deadline: $DEADLINE_UTC (${HOURS_LEFT}h ${MINS_LEFT}m left)"
echo "Urgency: $URGENCY"
echo ""
echo "Stages:"
echo "$STAGES" | sed 's/^/  /'
echo ""
if [ "$PROOFS_PENDING" -gt 0 ]; then
  echo "⚠️  DRI-ACTION-NEEDED — $PROOFS_PENDING proof(s) sitting in open PRs. Merge-check is P1 this cycle:${PENDING_PRS}"
fi
if [ "$PROOF_COUNT" -lt 3 ] && [ "$HOURS_LEFT" -le 6 ]; then
  echo "⚠️  P1 TRIGGER — sales-dri worker must be dispatched this cycle."
fi
